// <auto-generated />
using System;
using CCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCenter.Data.Migrations
{
    [DbContext(typeof(CCenterDbContext))]
    [Migration("20260105143842_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCenter.Data.Entities.Area", b =>
                {
                    b.Property<int>("IDArea")
                        .HasColumnType("int")
                        .HasColumnName("IDArea");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDArea", "AreaName");

                    b.ToTable("ccRIACat_Areas", "dbo");
                });

            modelBuilder.Entity("CCenter.Data.Entities.LoginEvent", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<short>("Extension")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<byte>("TipoMov")
                        .HasColumnType("tinyint")
                        .HasColumnName("TipoMov");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("LogId");

                    b.HasIndex("UserId", "Fecha");

                    b.ToTable("ccloglogin", "dbo");
                });

            modelBuilder.Entity("CCenter.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDArea")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("ccUsers", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
